In [2]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [9]:
a[0]

np.int64(1)

In [11]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [13]:
a[:3]

array([10,  2,  3])

In [15]:
b = a[3:]
b
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [16]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1, 3] #type

np.int64(8)

In [ ]:
a.ndim# check dimension

2

In [ ]:
a.shape
len(a.shape) == a.ndim#checking the shape

True

In [24]:
a.size
import math
a.size == math.prod(a.shape)

True

In [26]:
a.dtype

dtype('int64')

In [27]:
np.zeros(2)

array([0., 0.])