# `Numpy` For Data Science:

In [1]:
import numpy as np

In [2]:
a= np.arange(6)  # a range  
print(a)

[0 1 2 3 4 5]


In [3]:
a2=a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [4]:
a2=a[:, np.newaxis]
print(a2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [5]:
a3= a2[np.newaxis, :]
print(a3)

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


In [6]:
a3=a2[:, np.newaxis]
print(a3)

[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]]


# Creating Arrays with Numpy:

In [7]:
aa=np.array([0,1,2,3,4,5])
bb=np.array([(0,1,2,3,4,5), (6,7,8,9,10,11)])

In [8]:
aa.shape

(6,)

In [9]:
bb.shape

(2, 6)

# Initialization Array:

In [10]:
a4=np.zeros([2,5])
print(a4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
b1=np.ones([2,4])
print(b1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
c5=np.full([2,5], 4)
print(c5)

[[4 4 4 4 4]
 [4 4 4 4 4]]


# Creating a `identity matrix`:

In [13]:
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Array Atribute:

In [14]:
a.shape #shape of the array

(6,)

In [15]:
len(a)    #length of the elements of the array

6

In [16]:
a.ndim    #diamention of the array

1

In [17]:
a.size #size which is the numbers of the elements in array

6

In [18]:
a2.ndim

2

# Basics operations:

In [19]:
print(aa)
print(bb)

[0 1 2 3 4 5]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [20]:
g = aa-bb
g

array([[ 0,  0,  0,  0,  0,  0],
       [-6, -6, -6, -6, -6, -6]])

In [21]:
g = bb- aa
g

array([[0, 0, 0, 0, 0, 0],
       [6, 6, 6, 6, 6, 6]])

In [22]:
f= np.subtract(aa, bb)
f

array([[ 0,  0,  0,  0,  0,  0],
       [-6, -6, -6, -6, -6, -6]])

In [23]:
h= aa +bb
h

array([[ 0,  2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14, 16]])

In [24]:
s= np.add(aa, bb)
s

array([[ 0,  2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14, 16]])

In [25]:
t= np.multiply(aa, bb)
t

array([[ 0,  1,  4,  9, 16, 25],
       [ 0,  7, 16, 27, 40, 55]])

In [26]:
u = aa * bb
u

array([[ 0,  1,  4,  9, 16, 25],
       [ 0,  7, 16, 27, 40, 55]])

In [27]:
v= aa / bb
v

C:\Users\Summaiya\AppData\Local\Temp\ipykernel_11880\2381988521.py:1: RuntimeWarning: invalid value encountered in divide
  v= aa / bb


array([[       nan, 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ,
        0.45454545]])

In [28]:
w= aa** 2
w

array([ 0,  1,  4,  9, 16, 25])

In [29]:
empty=np.empty((2,3))
print(empty)
print(empty[1])

[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]


## Numpy part-2:

In [30]:
odd= np.arange(0,24,3)
odd

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [31]:
even= np.arange(0,10,2)
even

array([0, 2, 4, 6, 8])

# Linear space:(sequence data):

In [32]:
lin= np.linspace(0, 98, num=10)
lin

array([ 0.        , 10.88888889, 21.77777778, 32.66666667, 43.55555556,
       54.44444444, 65.33333333, 76.22222222, 87.11111111, 98.        ])

# Define the dtype of array: 

In [33]:
x = np.ones(2, dtype=np.int64) 
x

array([1, 1])

In [34]:
y= np.ones(5, dtype=np.float64)
y

array([1., 1., 1., 1., 1.])

# Sorting the array:

In [35]:
sort=np.array([1,3,2,5,4,8,7,6])
np.sort(sort)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
x=np.array([[1,2], [3,4]])
y=np.array([[5,6], [7,8]])


In [37]:
z=np.concatenate((x,y), axis=1)