# `Numpy` For Data Science:

In [2]:
import numpy as np

In [3]:
a= np.arange(6)  # a range  
print(a)

[0 1 2 3 4 5]


In [4]:
a2=a[np.newaxis, :]
print(a2)

[[0 1 2 3 4 5]]


In [5]:
a2=a[:, np.newaxis]
print(a2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [6]:
a3= a2[np.newaxis, :]
print(a3)

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]]]


In [7]:
a3=a2[:, np.newaxis]
print(a3)

[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]]


# Creating Arrays with Numpy:

In [8]:
aa=np.array([0,1,2,3,4,5])
bb=np.array([(0,1,2,3,4,5), (6,7,8,9,10,11)])

In [9]:
aa.shape

(6,)

In [10]:
bb.shape

(2, 6)

# Initialization Array:

In [11]:
a4=np.zeros([2,5])
print(a4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
b1=np.ones([2,4])
print(b1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
c5=np.full([2,5], 4)
print(c5)

[[4 4 4 4 4]
 [4 4 4 4 4]]


# Creating a `identity matrix`:

In [14]:
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Array Atribute:

In [15]:
a.shape #shape of the array

(6,)

In [16]:
len(a)    #length of the elements of the array

6

In [17]:
a.ndim    #diamention of the array

1

In [18]:
a.size #size which is the numbers of the elements in array

6

In [19]:
a2.ndim

2

# Basics operations:

In [20]:
print(aa)
print(bb)

[0 1 2 3 4 5]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [21]:
g = aa-bb
g

array([[ 0,  0,  0,  0,  0,  0],
       [-6, -6, -6, -6, -6, -6]])

In [22]:
g = bb- aa
g

array([[0, 0, 0, 0, 0, 0],
       [6, 6, 6, 6, 6, 6]])

In [23]:
f= np.subtract(aa, bb)
f

array([[ 0,  0,  0,  0,  0,  0],
       [-6, -6, -6, -6, -6, -6]])

In [24]:
h= aa +bb
h

array([[ 0,  2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14, 16]])

In [25]:
s= np.add(aa, bb)
s

array([[ 0,  2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14, 16]])

In [26]:
t= np.multiply(aa, bb)
t

array([[ 0,  1,  4,  9, 16, 25],
       [ 0,  7, 16, 27, 40, 55]])

In [27]:
u = aa * bb
u

array([[ 0,  1,  4,  9, 16, 25],
       [ 0,  7, 16, 27, 40, 55]])

In [28]:
v= aa / bb
v

C:\Users\Summaiya\AppData\Local\Temp\ipykernel_8060\2381988521.py:1: RuntimeWarning: invalid value encountered in divide
  v= aa / bb


array([[       nan, 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ,
        0.45454545]])

In [29]:
w= aa** 2
w

array([ 0,  1,  4,  9, 16, 25])

In [30]:
empty=np.empty((2,3))
print(empty)
print(empty[1])

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.29062229e-306 2.22521646e-306 4.79243676e-322]]
[1.29062229e-306 2.22521646e-306 4.79243676e-322]


## Numpy part-2:

In [31]:
odd= np.arange(0,24,3)
odd

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [32]:
even= np.arange(0,10,2)
even

array([0, 2, 4, 6, 8])

# Linear space:(sequence data):

In [33]:
lin= np.linspace(0, 98, num=10)
lin

array([ 0.        , 10.88888889, 21.77777778, 32.66666667, 43.55555556,
       54.44444444, 65.33333333, 76.22222222, 87.11111111, 98.        ])

# Define the dtype of array: 

In [34]:
x = np.ones(2, dtype=np.int64) 
x

array([1, 1])

In [35]:
y= np.ones(5, dtype=np.float64)
y

array([1., 1., 1., 1., 1.])

# Sorting the array:

In [36]:
sort=np.array([1,3,2,5,4,8,7,6])
np.sort(sort)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
x=np.array([[1,2], [3,4]])
y=np.array([[5,6], [7,8]])


In [38]:
z=np.concatenate((x,y), axis=1)

## Matrix in Numpy lib:

In [39]:
matrixs= np.arange(0, 100, 2).reshape(5,10)
matrixs

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [40]:
matrixs[0:3, 3:5]

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [41]:
matrixs[0:, 3:5 ]

array([[ 6,  8],
       [26, 28],
       [46, 48],
       [66, 68],
       [86, 88]])

In [42]:
matrixs[: , :]

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [43]:
matrixs.min()

np.int64(0)

In [44]:
matrixs.max()

np.int64(98)

In [45]:
matrixs.sum()

np.int64(2450)

In [46]:
matrixs.max(axis=0)

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [47]:
matrixs.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
matrixs.max(axis=1)

array([18, 38, 58, 78, 98])

In [49]:
matrixs.min(axis=1)

array([ 0, 20, 40, 60, 80])

In [65]:
arr = np.arange(0, 52, 2).reshape(2, 13)
arr


array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]])

In [59]:
m= np.arange(0, 20, 2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [60]:
m+np.array([20,22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])